VAGRANTFILE_API_VERSION = "2"

HOSTNAME      = "chefserver"
HOSTIP        = "192.168.128.40"
SYNCFOLDER    = "../shared"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/precise64"
  config.vm.box_check_update = false
  config.vm.network :private_network, ip: HOSTIP
  config.vm.define HOSTNAME do |host|
  end

  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", 1024]
    vbox.name = HOSTNAME
  end

  config.vm.provision :file do |file|
    file.source      = "~/Desktop/Stuff/Chef/chef-server/chef-server_11.1.4-1_amd64.deb"
    file.destination = "/home/vagrant/chef-server_11.1.4-1_amd64.deb"
  end

  config.vm.synced_folder "../shared", "/shared"

  config.vm.provision "shell" do |s|
    s.path = "../shared/apt-update.sh"
  end

  config.vm.provision "shell" do |s|
    s.path = "../shared/gitsetup.sh"
  end

  config.vm.provision "shell" do |s|
    s.path = "../shared/chefserver.sh"
  end
end
