VAGRANTFILE_API_VERSION = "2"

HOSTNAME = "chefws"
HOSTIP   = "192.168.128.41"



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/precise64"

  config.vm.define "chefws" do |guest|
    guest.vm.network :private_network, ip: "192.168.128.41"
    guest.vm.provider :virtualbox do |vbox|
      vbox.name = "chefws"
    end

    guest.vm.synced_folder "../shared", "/shared"

    guest.vm.provision "shell" do |s|
      s.path = "../shared/chefclient.sh"
    end

    guest.vm.provision :file do |file|
      file.source      = "/Users/mrajani/.gitconfig"
      file.destination = "/home/vagrant/.gitconfig"
    end

    guest.vm.provision :file do |file|
      file.source      = "/Users/mrajani/.ssh/github_rsa"
      file.destination = "/home/vagrant/.ssh/id_rsa"
    end

    guest.vm.provision :file do |file|
      file.source      = "/Users/mrajani/.ssh/github_rsa.pub"
      file.destination = "/home/vagrant/.ssh/id_rsa.pub"
    end
  end

end
