- hosts: "{{ vagrant_hosts | default('all') }}"
  gather_facts: True
  vars_files:
    - /shared/vars_{{ ansible_os_family | lower }}.yml
  tasks:
    - name: Install Packages
      include_tasks: /shared/pkgs_{{ ansible_os_family | lower }}.yml

    - name: Setup my git config
      include_tasks: /shared/gitsetup.yml

- name: No Op Playbook
  import_playbook: /shared/noop.yml
