VAGRANTFILE_API_VERSION = "2"


hostname = "sslhost"
hostip   = "192.168.128.187"
synced_folder = "~/Documents/Git/learnvagrant/shared"
domain   = "iono.corp"
box      = "bento/centos-6.7"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = box
  config.vm.box_check_update = false
  config.vm.hostname = "#{hostname}.#{domain}"
  
  config.vm.define hostname do |guest|
    guest.vm.network :private_network, ip: hostip
    guest.vm.provider :virtualbox do |vbox|
      vbox.name = "c_" + hostname
    end
    
    guest.vm.provider :virtualbox do |vbox|
      #vbox.customize ["modifyvm", :id, "--nic2", "intnet", "--intnet2", "blah"]
    end

    guest.vm.synced_folder synced_folder, "/shared"

    guest.vm.provision "shell" do |sh|
      sh.path = "#{synced_folder}/gitsetup.sh"
    end

    guest.vm.provision "shell" do |sh|
      sh.path = "#{synced_folder}/gitinstall.sh"
      sh.args = "centos"
    end

    guest.vm.provision "shell" do |sh|
      sh.path = "#{synced_folder}/provision.sh"
    end
  end

end
