VAGRANTFILE_API_VERSION = "2"


hostname = "webby"
hostip   = "192.168.128.98"
synced_folder = "~/Documents/Git/learnvagrant/shared"
domain   = "iono.corp"
box      = "bento/centos-7.2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = box
  config.vm.box_check_update = false
  config.vm.hostname = "#{hostname}.#{domain}"
  # config.vm.network :forwarded_port, guest: 22, host: 2241
  config.vm.define hostname do |guest|
    guest.vm.network :private_network, ip: hostip
    guest.vm.provider :virtualbox do |vbox|
      vbox.name = "centos_" + hostname
    end

    guest.vm.provider :virtualbox do |vbox|
      # These options are for VBoxManage modifyvm
      #vbox.customize ["modifyvm", :id, "--nic2", "intnet", "--intnet2", "NET2"]
      vbox.name = hostname
    end

    guest.vm.synced_folder synced_folder, "/shared"

    guest.vm.provision "shell" do |sh|
      sh.path = "#{synced_folder}/gitsetup.sh"
    end

    guest.vm.provision "shell" do |sh|
      sh.path = "#{synced_folder}/gitinstall.sh"
      sh.args = "centos"
    end

    guest.vm.provision "shell" do |sh|
      sh.path = "#{synced_folder}/provision.sh"
    end
  end

end
