VAGRANTFILE_API_VERSION = "2"

hostname      = "node01"
hostip        = "192.168.128.49"
synced_folder = "../shared"
box           = "ubuntu/trusty64"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = box
  config.vm.box_check_update = false

  config.vm.define hostname do |guest|
    guest.vm.network :private_network, ip: hostip
    guest.vm.provider :virtualbox do |vbox|
      vbox.name = "trusty_" + hostname
    end

    guest.vm.synced_folder synced_folder, "/shared"

#    guest.vm.provision :file do |file|
#      file.source      = "/Users/mrajani/.gitconfig"
#      file.destination = "/home/vagrant/.gitconfig"
#    end

#    guest.vm.provision :file do |file|
#      file.source      = "../shared/git_rsa"
#      file.destination = "/home/vagrant/.ssh/id_rsa"
#    end

#    guest.vm.provision :file do |file|
#      file.source      = "../shared/git_rsa.pub"
#      file.destination = "/home/vagrant/.ssh/id_rsa.pub"
#    end

    guest.vm.provision "shell" do |sh|
      sh.path = "#{synced_folder}/gitsetup.sh"
    end

    guest.vm.provision "shell" do |sh|
      sh.path = "#{synced_folder}/gitinstall.sh"
      sh.args = "ubuntu"
    end
  end
end

