require 'yaml'
require 'pp'
VAGRANTFILE_API_VERSION = "2"

node = YAML.load_file(File.open("vagrant.yml"))['nodes']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = node['box']
  config.vm.box_check_update = false
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.hostname = node['hostname']
  config.hostmanager.aliases = node['aliases'] if defined?(node['aliases'])


  config.vm.define node['hostname'] do |guest|
    guest.vm.network :private_network, ip: node['ip']
    if node['gport'] && node['hport']
      guest.vm.network :forwarded_port, guest: node['gport'], host: node['hport']
    end
    guest.vm.provider :virtualbox do |vbox|
      vbox.name = "u" + node['ip'].split('.')[-1] + "-" + node['hostname'] 
      vbox.customize ["modifyvm", :id, "--memory", node['memory']]
    end

    node['shared'].each do |mnt|
      guest.vm.synced_folder mnt, "/#{mnt}"
    end

    node['shell'].each do |script|
      guest.vm.provision :shell do |sh|
        sh.path = script['path']
        sh.args = script['args'] if defined?(script['args'])
      end
    end

  end
end
