Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "docker" do |d|
    d.run "hello-world",
      cmd: "bash -l",
      args: "-v '/vagrant:/var/www'"
    d.pull_images "rabbitmq"
    d.pull_images "laltopi/tcserver:0.2.0"
  end
end
