VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/precise64"

  config.vm.define "chefserver" do |config|
    config.vm.network :private_network, ip: "192.168.128.40"
    config.vm.provider :virtualbox do |vbox|
      vbox.name = "chefserver"
    end
    config.vm.provision "shell" do |s|
      s.path = "provision.sh"
    end
  end

config.vm.define "chefws" do |config|
  config.vm.network :private_network, ip: "192.168.128.41"
  config.vm.provider :virtualbox do |vbox|
    vbox.name = "chefws"
  end
  config.vm.provision "shell" do |s|
    s.path = "provision.sh"
  end
end


end
