VAGRANTFILE_API_VERSION = "2"

hostname = "puppetmaster4"
hostip   = "192.168.128.164"
domain   = "iono.vm"
box      = "bento/centos-6.7"
synced_folder    = "~/Documents/Git/learnvagrant/shared"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = box
  config.vm.box_check_update = true
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = false
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.network :private_network, ip: hostip
  config.vm.hostname = "#{hostname}.#{domain}"
  config.hostmanager.aliases = %w(puppet)
  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", 1024]
    vbox.name = hostname + "-"+ hostip.split('.')[-1]
  end

  config.vm.synced_folder synced_folder, "/shared"

  config.vm.provision "provision", type: "shell" do |sh|
    sh.path = "#{synced_folder}/provision.sh"
  end

  config.vm.provision "shell" do |sh|
    sh.path = "#{synced_folder}/gitsetup.sh"
  end

  config.vm.provision "shell" do |s|
    s.path = "#{synced_folder}/gitinstall.sh"
    s.args = "centos"
  end

  config.vm.provision "shell" do |s|
    s.path = "#{synced_folder}/puppetmaster4.sh"
    s.args = " #{hostip} #{hostname} #{domain}"
  end
end
