VAGRANTFILE_API_VERSION = "2"

HOSTNAME = "puppetmaster"
HOSTIP   = "192.168.128.50"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "chef/centos-6.5"
  config.vm.box_check_update = false

  config.vm.define HOSTNAME do |guest|
    guest.vm.network :private_network, ip: HOSTIP
    guest.vm.provider :virtualbox do |vbox|
      vbox.name = HOSTNAME
    end

    guest.vm.synced_folder "../shared", "/shared"

    guest.vm.provision :file do |file|
      file.source      = "/Users/mrajani/.gitconfig"
      file.destination = "/home/vagrant/.gitconfig"
    end

    guest.vm.provision :file do |file|
      file.source      = "../shared/git_rsa"
      file.destination = "/home/vagrant/.ssh/id_rsa"
    end

    guest.vm.provision :file do |file|
      file.source      = "../shared/git_rsa.pub"
      file.destination = "/home/vagrant/.ssh/id_rsa.pub"
    end

    guest.vm.provision "shell" do |s|
      s.path = "../shared/puppetmaster.sh"
      s.args = " #{HOSTIP} #{HOSTNAME}"
    end

  end

end
